### ISSUE TITLE
Compatibility with Spree 2.0

### ISSUE THREAD

**Issue by dfischer** [suryart/spree_active_sale#26]
How is compatibility with Spree 2.0?

http://spreecommerce.com/blog/spree-2-0-0-released

**Comment by suryart** [comment]
I've already been working on this. https://github.com/suryart/spree_active_sale/tree/2-0-0-beta
Needs to resume the work on this sometime soon.

**Comment by dfischer** [comment]
Awesome. I will stay up to date.

**Comment by suryart** [comment]
Here it is: https://github.com/suryart/spree_active_sale/tree/2-0-stable
