### ISSUE TITLE
Sale EventCounter not Working.,

### ISSUE THREAD

**Issue by teamerjasonrao99** [suryart/spree_active_sale#27]
Hi guys,

I am having problem with 'Active Sale Event countdown timer'. Its shows me static date like Sale Close in 2 days 1:16:20 but it doesn't continue countdown....

Any Clue Guys.?
Thanks.

**Comment by suryart** [comment]
Can you please tell me the steps to regenerate the issue? So that, I can fix it?

One of the reasons could be attribute not being set properly. Is `spree_active_sale/event_timer.js` being included on the page?

Or use <%= sale_event_timer(active_sale_event) %> `sale_event_timer` helper and pass Spree::ActiveSaleEvent's object to it.

**Comment by teamerjasonrao99** [comment]
Thanks Surya,

  I have just added some CSS in the file
spree_active_sale/_sale_events.html.erb and it became inactive. Countdown
is working in my spree branch having no custom design included so this
issue seems to be with my Custom css.What you say if it can happen by some
css classes?
 Yes event_timer.js  is included in the page source.

**Comment by suryart** [comment]
Basically, the span/div should have data-timer=DateTimeObject assigned.

For example: `<span class="sale_event_message" data-layout="{dn} DAYS {hnn}{sep}{mnn}{sep}{snn}" data-timer="2013-09-25T12:39:00">71 DAYS 08:46:46</span>`

was it working before adding css classes?

**Comment by teamerjasonrao99** [comment]
Actually i have following in my _sales_event.html.erb for countdown

<div class="tprodTimer"><%= sale_event_timer(sale_event) %></div>

And in my Console i can see the error \* "Uncaught TypeError[objectobject]
has no method countdown". in "event_timer.js?body=1"*

Please see the error in attachments.

Any clue?

Thanks.

**Comment by teamerjasonrao99** [comment]
I can see following code in my page source code.

_<span class="sale_event_message">SALE CLOSES IN</span> <span class="
sale_event_message_timer" data-layout="{dn} DAYS {hnn}{sep}{mnn}{sep}{snn}"
data-timer="2013-07-16T08:31:17">2013-07-16T08:31:17_*</span>
*
Thanks.

**Comment by suryart** [comment]
I think this is jquery issue. a css class "hasCountdown" should automatically be appended to span which has data-timer attribute after page load.

Can you please specify your Gemfile? So that, I can run a test app against your Gemfile data and see what I can find?

**Comment by suryart** [comment]
Hey @teamerjasonrao99,

Are you still facing this issue? Kindly update.

**Comment by teamerjasonrao99** [comment]
Hi there,

No it was a jquery issue thanks.
Thanks.

--Jason
