### ISSUE TITLE
Admin interface for flash sales

### ISSUE THREAD

**Issue by dfischer** [suryart/spree_active_sale#3]

**Comment by dfischer** [comment]
@suryart any progress on this? I'd say this is probably highest priority to make this usable.

**Comment by suryart** [comment]
@dfischer Yes, you're right. I'll be working on admin interface this week.

**Comment by suryart** [comment]
Admin interface is ready!! Pretty ugly, still needed some styling and optimization. https://github.com/suryart/spree_active_sale/commit/f15cf75006cce0a977a1919e8bb9127e4159d7cd

**Comment by dfischer** [comment]
How do you see this? I made Gemfile use `gem 'spree_active_sale' , :git => 'git://github.com/suryart/spree_active_sale.git'` and when I go to admin area I don't see anything different? I tried /admin/events and that doesn't work either.

**Comment by suryart** [comment]
Oh, that's on "1-1-0" branch currently. I was thinking of sorting all the issues and then publish/ merge it to master.

For now, you can use:

`gem 'spree_active_sale' , :git => 'git://github.com/suryart/spree_active_sale.git', :branch => '1-1-0'`
