### ISSUE TITLE
Issue with conflict in Gemfile when using spree_active_sale and spree 2-2-stable

### ISSUE THREAD

**Issue by FaiqAdam** [suryart/spree_active_sale#32]
I got error message 

Bundler could not find compatible versions for gem "spree_core":
In Gemfile:
spree_active_sale (~> 2.0.0) ruby depends on
spree_core (~> 2.0.0) ruby spree (>= 0) ruby depends on
spree_core (2.2.2.beta)

my gem file is

gem 'rails', '4.0.4'
gem 'sqlite3'
gem 'spree', github: 'spree/spree', branch: '2-2-stable'
gem 'spree_auth_devise', github: 'spree/spree_auth_devise', branch: '2-2-stable'

gem 'spree_active_sale' , :git => 'git://github.com/suryart/spree_active_sale.git', :branch => '2-0-stable'

**Comment by suryart** [comment]
It's because spree_active_sale '2-0-stable' branch is not compatible with Spree 2-2-stable.

**Comment by suryart** [comment]
@FaiqAdam - are you still getting this error? please confirm.

**Comment by suryart** [comment]
Closing this issue as reporter has not responded in considerable amount of time.
