### ISSUE TITLE
Admin: New event? What does it include?

### ISSUE THREAD

**Issue by dfischer** [suryart/spree_active_sale#7]
When I create a new event, I'm not sure what I'm including in the "flash sale?"

When I create a new event, I assume two things.

1) I can select a product to be featured in this sale.
2) I can select a group of products to be listed (taxon), with one being featured and the other being in a "sidebar, e.g view other sales"

Right now I can't seem to do either? It just gives me an option for the flash sale name, and description. But no ability to select a product or taxon. Although there is an "eventable" option but no idea what that means.

**Comment by suryart** [comment]
UI needs to be changed here. Just to make it work as soon as possible, I added a drop down named "eventable" which can be a product or a taxon(i.e. group of products), once you select one of them(product/taxon), in permalink you need to write the product's/ taxon's permalink to link the event accordingly. 

Well, to make this simple and easy. I guess, there should be a drop down and a text box. In drop down asks if you wanna add a product or a taxon? if product is selected and when you start writing the name of a product in text box, it should start listing them in it(just like auto complete suggestions). And, when you select a product from list, it should gets added as an event.

Let me know if this solves your doubts?

**Comment by dfischer** [comment]
Yes,

I'd recommend using a select drop-down with all the options then utilizing Chosen to create an "autocomplete" or "scroll to select" option. Potentially the multiple select field may be good.

This way you don't have to write ajax logic or any of that. Just feed it through Chosen plugin and list all options.

**Comment by suryart** [comment]
Will work on it when testing is done for sure.

**Comment by dfischer** [comment]
Getting exciting!
